[buf]
format = "(with [$symbol$version ]($style))"
symbol = "ï’ "

[bun]
format = "(via [$symbol($version )]($style))"

[c]
format = "(via [$symbol($version(-$name) )]($style))"
symbol = "î˜ "

[cmake]
format = "(via [$symbol($version )]($style))"

[cobol]
format = "(via [$symbol($version )]($style))"

[crystal]
format = "(via [$symbol($version )]($style))"

[daml]
format = "(via [$symbol($version )]($style))"

[dart]
format = "(via [$symbol($version )]($style))"
symbol = "î˜ "

[deno]
format = "(via [$symbol($version )]($style))"

[dotnet]
format = "(via [$symbol($version )(ğŸ¯ $tfm )]($style))"

[elixir]
format = "(via [$symbol($version \\(OTP $otp_version\\) )]($style))"
symbol = "î‰µ "

[elm]
format = "(via [$symbol($version )]($style))"
symbol = "î˜¬ "

[erlang]
format = "(via [$symbol($version )]($style))"

[fennel]
format = "(via [$symbol($version )]($style))"

[golang]
format = "(via [$symbol($version )]($style))"
symbol = "î˜§ "

[haskell]
format = "(via [$symbol($version )]($style))"
symbol = "î· "

[helm]
format = "(via [$symbol($version )]($style))"

[java]
format = "(via [$symbol($version )]($style))"
symbol = "î‰– "

[julia]
format = "(via [$symbol($version )]($style))"
symbol = "î˜¤ "

[kotlin]
format = "(via [$symbol($version )]($style))"

[lua]
format = "(via [$symbol($version )]($style))"
symbol = "î˜  "

[nim]
format = "(via [$symbol($version )]($style))"
symbol = "ó°†¥ "

[nodejs]
format = "(via [$symbol($version )]($style))"
symbol = "îœ˜ "

[ocaml]
format = "(via [$symbol($version )(\\($switch_indicator$switch_name\\) )]($style))"

[opa]
format = '(via [$symbo($version ]($style))"'

[package]
format = "(is [$symbol$version]($style) )"
symbol = "ó°— "

[perl]
format = "(via [$symbol($version )]($style))"

[php]
format = "(via [$symbol($version )]($style))"

[purescript]
format = "(via [$symbol($version )]($style))"

[python]
format = "(via [${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\) )]($style))"
symbol = "îˆµ "

[raku]
format = "(via [$symbol($version-$vm_version )]($style))"

[red]
format = "(via [$symbol($version )]($style))"

[rlang]
format = "(via [$symbol($version )]($style))"
symbol = "ó°Ÿ” "

[ruby]
format = "(via [$symbol($version )]($style))"
symbol = "î‘ "

[rust]
format = "(via [$symbol($version )]($style))"
symbol = "î¨ "

[scala]
format = "(via [$symbol($version )]($style))"
symbol = "îœ· "

[swift]
format = "(via [$symbol($version )]($style))"

[vagrant]
format = "(via [$symbol($version )]($style))"

[vlang]
format = "(via [$symbol($version )]($style))"

[zig]
format = "(via [$symbol($version )]($style))"

[aws]
symbol = "îŒ½  "

[conda]
symbol = "ï„Œ "

[directory]
read_only = " ó°Œ¾"

[docker_context]
symbol = "ïŒˆ "

[fossil_branch]
symbol = "ï˜ "

[git_branch]
symbol = "ï˜ "

[guix_shell]
symbol = "ïŒ¥ "

[haxe]
symbol = "î™¦ "

[hg_branch]
symbol = "ï˜ "

[hostname]
ssh_symbol = "î¬ "

[memory_usage]
symbol = "ó°› "

[meson]
symbol = "ó°”· "

[nix_shell]
symbol = "ïŒ“ "

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Windows = "ó°² "

[pijul_channel]
symbol = "ï˜ "
